spring:
  web:
    resources:
      add-mappings: true
      cache:
        cachecontrol:
          #缓存响应时间，单位秒
          max-age: 3600
      chain:
        #资源配链启动缓存，默认启动
        cache: true
        #启动资源链，默认禁用
        enabled: true
        #启用压缩资源（gzip，brotil）解析，默认禁用
        compressed: true
      static-locations: classpath:/static/
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      # 空闲连接存活最大时间默认600000（10分钟）
      idle-timeout: 1800000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 3000
      connection-test-query: SELECT 1
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        #最大连接数 默认8
        max-active: 8
        #最大连接阻塞时间
        max-wait: 1000ms
        #最大空闲连接，默认8
        max-idle: 200

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.zhx.seckilldemo

logging:
  level:
    com.example.sekilldemo.mapper: debug